export default [
    'New York',
    'London',
    'Tokyo',
    'Beijing',
    'Los Angeles',
    'Shanghai',
    'Hong Kong',
    'Paris',
    'Madrid',
    'Singapore',
    'Seoul',
    'Mumbai',
    'Moscow',
    'Sao Paulo',
    'Istanbul',
    'Jakarta',
    'Berlin',
    'Bangkok',
    'Mexico City',
    'Dubai',
    'San Francisco',
    'Rome',
    'Sydney',
    'Taipei',
    'Lagos',
    'Kolkata',
    'Cairo',
    'Miami',
    'Barcelona',
    'Buenos Aires',
    'Sky Blue',
    'Off White',
    'Prussian Blue',
    'Mint Green',
    'Cyan',
    'Lavender',
    'Maroon',
    'Mustard Yellow',
    'Teal',
    'Coral',
    'Olive Green',
    'Slate Gray',
    'Chartreuse',
    'Steel Blue',
    'Dark Magenta',
    'Mauve',
    'Crimson',
    'Burnt Orange',
    'Dusty Rose',
    'Scarlet',
    'Fuchsia',
    'Cobalt Blue',
    'Lime Green',
    'Aqua',
    'Royal Blue',
    'Honeydew',
    'Salmon',
    'Daffodil',
    'Sandy Brown',
    'Moss Green',
    'Cat',
    'Dog',
    'Fire Hydrant',
    'Building',
    'Car',
    'Plane',
    'Tree',
    'Cloud',
    'River',
    'Mountain',
    'Ocean',
    'Star',
    'Moon',
    'Sun',
    'Phone',
    'Computer',
    'Pen',
    'Book',
    'Chair',
    'Table',
    'Cathedral',
    'Museum',
    'Garden',
    'Street',
    'Bridge',
    'Factory',
    'School',
    'Hospital',
    'Cliff',
    'Stadium',
    'Cave',
    'StarShaper',
    'GalaxyWalker',
    'CosmicBinder',
    'AstroLifter',
    'SunGazer',
    'MoonStalker',
    'EclipseRider',
    'DuskSlayer',
    'NightBringer',
    'VoidBreaker',
    'TimeWeaver',
    'VortexLord',
    'TitanTamer',
    'StormRaiser',
    'DragonRider',
    'FireBreaker',
    'LightningMaker',
    'SpaceStriker',
    'NebulaKeeper',
    'GalaxyGuardian',
    'CosmosMaster',
]
